---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-app
  template:
    metadata:
      labels:
        app: demo-app
    spec:
      containers:
        - env:
            - name: APP_FORTUNE_SOURCE
              value: file
          image: dhananjay12/demo-app:2.0.0
          imagePullPolicy: Always
          name: demo-app
          ports:
            - containerPort: 8080
          resources: {}
      restartPolicy: Always
status: {}

---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: demo-app
  name: demo-app
  namespace: dev
spec:
  type: LoadBalancer #default ClusterIP
  ports:
    - protocol: "TCP" #default anyways
      port: 8082
      targetPort: 8080
  selector:
    app: demo-app