apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: frontend
  namespace: frontend
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/chart-image: "semver:*"
spec:
  releaseName: frontend
  targetNamespace: frontend
  chart:
    repository: https://dhananjay12.github.io/learn-helm
    name: mygithubcharts/generic-chart
    version: 0.0.1
  values:
    image:
      repository: dhananjay12/angular-test-versioning
      tag: 1.2.0
      pullPolicy: Always
    containerPort: 80
    service:
      httpPort: 80
      targetPort: 80
    ingress:
      enabled: false